13. Начинаем подготовку адаптивной графики в личном проекте
htmlacademy-adaptive/356085-pink-20 pull request #10
Opened 2020-09-02 09:46 UTC by AleksandrGV

2020-09-02 20:47 UTC, raccoonroman requested changes

2020-09-02 20:47 UTC, raccoonroman commented on source/photo.html
> +            <img class="user-story__link-img" src="img/panorama-mobile@1x.jpg" srcset="img/panorama-mobile@2x.jpg"
```suggestion
            <img class="user-story__link-img" src="img/panorama-mobile@1x.jpg" srcset="img/panorama-mobile@2x.jpg 2x"
```

2020-09-02 20:47 UTC, raccoonroman commented on source/photo.html
> +                    srcset="img/photo-car-mobile@2x.jpg" alt="Снимок автомобиля">
```suggestion
                    srcset="img/photo-car-mobile@2x.jpg 2x" alt="Снимок автомобиля">
```

2020-09-02 20:47 UTC, raccoonroman commented on source/photo.html
> +                    srcset="img/photo-drumset-mobile@2x.jpg" alt="Барабанная установка">
```suggestion
                    srcset="img/photo-drumset-mobile@2x.jpg 2x" alt="Барабанная установка">
```

2020-09-02 20:47 UTC, raccoonroman commented on source/photo.html
> +                    srcset="img/photo-window-mobile@2x.jpg" alt="Окна">
```suggestion
                    srcset="img/photo-window-mobile@2x.jpg 2x" alt="Окна">
```

2020-09-02 20:47 UTC, raccoonroman commented on source/photo.html
> +                    srcset="img/photo-fair-mobile@2x.jpg" alt="Кубанская бахча">
```suggestion
                    srcset="img/photo-fair-mobile@2x.jpg 2x" alt="Кубанская бахча">
```

2020-09-02 20:47 UTC, raccoonroman commented on source/photo.html
> +                    srcset="img/photo-pov-mobile@2x.jpg" alt="Выше всех">
```suggestion
                    srcset="img/photo-pov-mobile@2x.jpg 2x" alt="Выше всех">
```

2020-09-02 20:47 UTC, raccoonroman commented on source/photo.html
> +                    srcset="img/photo-wing-mobile@2x.jpg" alt="Закат с борта самолета">
```suggestion
                    srcset="img/photo-wing-mobile@2x.jpg 2x" alt="Закат с борта самолета">
```

2020-09-02 20:47 UTC, raccoonroman commented on source/index.html
> +                    srcset="img/iphone-screen-1-desktop@2x.png" alt="Реальный мир">
```suggestion
                    srcset="img/iphone-screen-1-desktop@2x.png 2x" alt="Реальный мир">
```

2020-09-02 20:47 UTC, raccoonroman commented on source/index.html
> +                    srcset="img/iphone-screen-1-desktop@2x.png" alt="Реальный мир">
если source тегов нет, то и тег picture не нужен.

2020-09-02 20:47 UTC, raccoonroman commented on source/index.html
> +                    srcset="img/iphone-screen-1-desktop@2x.png" alt="Реальный мир">
Вообще из трех пунктов преимуществ у третего на всех версиях есть картинка, которая меняется на разных версиях - здесь в помощь тег picrure. А для первых двух - картинки только на десктопе. У тебя сейчас 2 списка получается. https://prnt.sc/uah37w Так не должно быть. Список должен быть один. Потому что это нарушает критерий. https://up.htmlacademy.ru/adaptive/20/criteries#b4

2020-09-02 20:47 UTC, raccoonroman commented on source/less/blocks/hero.less
> +  @media (min-resolution: 2dppx) {
точно такой же миксин можно создать и назвать его `retina`, чтобы не писать эту длинную строку

2020-09-03 06:00 UTC, AleksandrGV commented on source/form.html
> +            <source media="(width: 960px)" srcset="img/logo-pink-white-desktop.svg">
Исправил

2020-09-03 06:01 UTC, AleksandrGV commented on source/form.html
> +            <source media="(width: 660px)" srcset="img/logo-pink-white-tablet.svg">
Исправил

2020-09-03 06:08 UTC, AleksandrGV commented on source/index.html
> +                srcset="img/iphone-hand-tablet@1x.png, img/iphone-hard-tablet@2x.png 2x">
Исправил

2020-09-03 06:10 UTC, AleksandrGV commented on source/index.html
> +              <img class="hero__img-picture" src="img/iphone-hand-mobile@1x.png" srcset="img/iphone-hand-mobile@2x.png"
Добавил всем.

2020-09-03 06:11 UTC, AleksandrGV commented on source/photo.html
> +            <img class="user-story__link-img" src="img/panorama-mobile@1x.jpg" srcset="img/panorama-mobile@2x.jpg"
Исправил

2020-09-03 06:11 UTC, AleksandrGV commented on source/photo.html
> +                    srcset="img/photo-car-mobile@2x.jpg" alt="Снимок автомобиля">
Исправил

2020-09-03 06:11 UTC, AleksandrGV commented on source/photo.html
> +                    srcset="img/photo-drumset-mobile@2x.jpg" alt="Барабанная установка">
Исправил

2020-09-03 06:11 UTC, AleksandrGV commented on source/photo.html
> +                    srcset="img/photo-window-mobile@2x.jpg" alt="Окна">
Исправил

2020-09-03 06:12 UTC, AleksandrGV commented on source/photo.html
> +                    srcset="img/photo-fair-mobile@2x.jpg" alt="Кубанская бахча">
Исправил

2020-09-03 06:12 UTC, AleksandrGV commented on source/photo.html
> +                    srcset="img/photo-pov-mobile@2x.jpg" alt="Выше всех">
Исправил

2020-09-03 06:12 UTC, AleksandrGV commented on source/photo.html
> +                    srcset="img/photo-wing-mobile@2x.jpg" alt="Закат с борта самолета">
Исправил

2020-09-03 06:45 UTC, AleksandrGV commented on source/less/blocks/hero.less
> +  @media (min-resolution: 2dppx) {
Сделал

2020-09-03 08:04 UTC, AleksandrGV commented on source/index.html
> +                    srcset="img/iphone-screen-1-desktop@2x.png" alt="Реальный мир">
Исправил и изменил верстку убрал второй список.

2020-09-03 08:09 UTC, AleksandrGV commented
Исправил все замечания.

2020-09-03 18:00 UTC, raccoonroman approved these changes
👍

2020-09-03 18:00 UTC, merged