15. Начинаем оптимизировать векторную и растровую графику
htmlacademy-adaptive/356085-pink-20 pull request #12
Opened 2020-09-05 14:20 UTC by AleksandrGV

2020-09-05 20:02 UTC, raccoonroman requested changes

2020-09-06 05:08 UTC, AleksandrGV commented on source/form.html
> +                <use xlink:href="img/sprite.svg#icon-twitter"></use>
Исправил

2020-09-06 05:14 UTC, AleksandrGV commented on source/less/blocks/socials.less
> +  display: block;
Исправил.

2020-09-06 05:19 UTC, AleksandrGV commented on source/less/blocks/socials.less
> +.developed {
Исправил.

2020-09-06 06:51 UTC, raccoonroman approved these changes

2020-09-06 06:51 UTC, merged