16. Завершаем оптимизировать векторную и растровую графику
htmlacademy-adaptive/356085-pink-20 pull request #13
Opened 2020-09-06 10:54 UTC by AleksandrGV

2020-09-06 13:50 UTC, raccoonroman requested changes
Обрати особое внимание на переполнение. Я привожу только несколько примеров, но протестировать нужно все. 
* https://prnt.sc/ucha9h - добавил один пункт меню
* https://prnt.sc/uchb4f таких модификаторов не должно быть. Я банально захочу добавить еще одно поле и получу это https://prnt.sc/uchbhu . Где-то бордер толще, где-то тоньше. И я не знаю, какой из модификаторов я должен использовать. Нужно придумать универсальное решение, при котором легко что-то добавить или удалить.
* Такого https://prnt.sc/uchg8r не должно быть. Я например, не могу просто взять и скопировать какой-то текст.

2020-09-06 13:50 UTC, raccoonroman commented on source/less/blocks/form.less
> +    &--tel-email::after {
если текста много, он не должен скрываться под иконками https://prnt.sc/uch3oa

2020-09-06 13:50 UTC, raccoonroman commented on source/less/blocks/form.less
> +  &:nth-child(2n+2) {
удобней использовать ключевые слова - `even` (четные), `odd` (нечетные).

2020-09-06 13:50 UTC, raccoonroman commented on source/less/blocks/form.less
> +  &:nth-child(2n+2) {
```suggestion
  &:nth-child(even) {
```

2020-09-07 18:28 UTC, AleksandrGV commented on source/less/blocks/form.less
> +    &--tel-email::after {
Исправил все пункты, кроме позиционирования тарифов.

2020-09-07 18:28 UTC, AleksandrGV commented on source/less/blocks/form.less
> +  &:nth-child(2n+2) {
Изменил.

2020-09-07 20:05 UTC, raccoonroman approved these changes

2020-09-07 20:08 UTC, merged