Module8 task1
htmlacademy-adaptive/356085-pink-20 pull request #14
Opened 2020-09-08 20:17 UTC by AleksandrGV

2020-09-10 18:29 UTC, raccoonroman requested changes

2020-09-10 18:29 UTC, raccoonroman commented on gulpfile.js
> +    .pipe(rename("style.min.css"))
в папку build так же должен попадать неминифицированый файл стилей https://up.htmlacademy.ru/adaptive/20/criteries#b25

2020-09-10 18:29 UTC, raccoonroman commented on gulpfile.js
> +  return gulp.src("source*.html")
что делает этот таск? Если он ничего не делает, может он и не нужен?

2020-09-10 18:29 UTC, raccoonroman commented on package.json
> +    "imagemin-webp": "^6.0.0"
эти пакеты нужны только для разработки, соответственно, с блока dependencies их нужно удалить с помощью консольной команды

2020-09-10 18:29 UTC, raccoonroman commented on source/css/style.css
> +@font-face{font-family:"Open Sans";font-style:normal;font-weight:400;src:url(../fonts/opensans.woff2) format("woff2"),url(../fonts/opensans.woff) format("woff")}@font-face{font-family:"Open Sans";fon
вообще всю папку `css` удали из папки `source`.

2020-09-10 18:29 UTC, raccoonroman commented on source/form.html
> +                d="M13.62,0.017L13.472,0L0,1.412v24.661l13.472,8.017l13.43-7.99l0.042-0.026V1.412L13.62,0.017z M25.019,12.127L13.495,5.334 l-0.001-0.104L13.407,5.28l-0.088-0.056v0.109L1.925,12.118V3.
подключай свг через use

2020-09-10 18:29 UTC, raccoonroman commented on source/form.html
> +            <svg class="developed__icon" id="Layer_1" xmlns:xlink="http://www.w3.org/1999/xlink"
удали лишние атрибуты

2020-09-10 18:29 UTC, raccoonroman commented on source/img/sprite.svg
> +<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www
этот файл можно удалить, он собирается автоматически

2020-09-10 18:29 UTC, raccoonroman commented on source/less/blocks/download-application.less
> +    background-image: url("../img/logo-apple.svg");
я бы вставил иконки в разметку через спрайт. Так удобней

2020-09-11 15:24 UTC, AleksandrGV commented on gulpfile.js
> +  return gulp.src("source*.html")
Удалил.

2020-09-11 15:30 UTC, AleksandrGV commented on package.json
> +    "imagemin-webp": "^6.0.0"
Исправил.

2020-09-11 17:16 UTC, AleksandrGV commented on source/form.html
> +                d="M13.62,0.017L13.472,0L0,1.412v24.661l13.472,8.017l13.43-7.99l0.042-0.026V1.412L13.62,0.017z M25.019,12.127L13.495,5.334 l-0.001-0.104L13.407,5.28l-0.088-0.056v0.109L1.925,12.118V3.
Исправил

2020-09-11 17:17 UTC, AleksandrGV commented on source/form.html
> +            <svg class="developed__icon" id="Layer_1" xmlns:xlink="http://www.w3.org/1999/xlink"
Исправил, подключил через use

2020-09-11 17:20 UTC, AleksandrGV commented on source/img/sprite.svg
> +<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www
Исправил

2020-09-11 17:20 UTC, AleksandrGV commented on source/less/blocks/download-application.less
> +    background-image: url("../img/logo-apple.svg");
Вставил через спрайт

2020-09-11 17:24 UTC, AleksandrGV commented on source/css/style.css
> +@font-face{font-family:"Open Sans";font-style:normal;font-weight:400;src:url(../fonts/opensans.woff2) format("woff2"),url(../fonts/opensans.woff) format("woff")}@font-face{font-family:"Open Sans";fon
Удалил папку

2020-09-11 17:31 UTC, AleksandrGV commented on gulpfile.js
> +    .pipe(rename("style.min.css"))
Исправил

2020-09-11 17:51 UTC, raccoonroman requested changes

2020-09-11 17:51 UTC, raccoonroman commented on gulpfile.js
> +exports.build = build
точку с запятой не забывай ставить

2020-09-11 17:51 UTC, raccoonroman commented on source/form.html
> +                  <svg class="form__item--icon" width="20" height="24">
https://up.htmlacademy.ru/adaptive/20/criteries#b5
Использование модификатора без блока или элемента, который он модифицирует

2020-09-11 17:57 UTC, AleksandrGV commented on gulpfile.js
> +exports.build = build
Исправил.

2020-09-11 18:14 UTC, raccoonroman approved these changes

2020-09-11 18:14 UTC, merged