18. Улучшаем скорость загрузки
htmlacademy-adaptive/356085-pink-20 pull request #15
Opened 2020-09-13 09:43 UTC by AleksandrGV

2020-09-13 20:16 UTC, raccoonroman requested changes

2020-09-14 14:22 UTC, AleksandrGV commented on gulpfile.js
> +function styles() {
Исправил.

2020-09-14 14:27 UTC, AleksandrGV commented on source/form.html
> +  <link rel="preloader" href="fonts/opensans.woff2" as="font" crossorigin="anonymous">
Исправил.

2020-09-14 14:30 UTC, AleksandrGV commented on source/form.html
> +              target="_blank" rel="noopener">HTMLAcademy</a>
Исправил.

2020-09-14 14:32 UTC, AleksandrGV commented on source/less/global/fonts.less
> +  display: swap;
Исправил.

2020-09-14 15:35 UTC, raccoonroman approved these changes

2020-09-14 15:35 UTC, merged