11. Завершаем вёрстку личного проекта
htmlacademy-adaptive/356085-pink-20 pull request #9
Opened 2020-08-29 07:12 UTC by AleksandrGV

2020-08-30 09:18 UTC, raccoonroman requested changes

2020-08-30 09:18 UTC, raccoonroman commented on source/less/blocks/form.less
> +.form__button-send {
можно создать миксин для зеленых кнопок, она встречается в трех местах (отправка формы и 2 попапа), так что есть смысл, чтобы не дублировать стили

2020-08-30 09:18 UTC, raccoonroman commented on source/less/blocks/rates.less
> +.hit {
это уже отдельный бэм-блок, который должен быть в своем файле. Но я бы сделал его бэм-элементом или модификатором

2020-08-30 09:18 UTC, raccoonroman commented on source/less/blocks/slider.less
> +  width: 6px;
для удобства пользователя (чтобы было проще попасть на кнопку) лучше их делать максимально большими, так как сейчас они слишком маленькие. Я бы сделал их размером 25*25px, то есть так, чтобы между ними по сути не было пространства. При этом чтобы все это выглядело как по макету. У активной кнопки размер тот самый будет, просто визуально она будет казаться больше

2020-08-30 09:18 UTC, raccoonroman commented on source/less/blocks/user-stories.less
> +  height: 40px;
здесь размер текста максимально ограничен. Всегда должно быть место для переполнения, так как текста когда-то может стать больше. Фиксированные размеры лучше заменить на паддинги.

2020-08-30 09:18 UTC, raccoonroman commented on source/photo.html
> +                      <div class="editing__toggle editing__toggle-contrast"></div>
```suggestion
                      <div class="editing__toggle editing__toggle-contrast"></div>
```
модификатор написан с ошибкой

2020-08-31 15:04 UTC, AleksandrGV commented on source/less/blocks/form.less
> +    background-image: url("data:image/svg+xml,%3Csvg version='1.0' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='21.698px' height='
Сделал отдельный файл для СВГ.

2020-08-31 15:18 UTC, AleksandrGV commented on source/less/blocks/form.less
> +.form__button-send {
Исправил.

2020-08-31 15:32 UTC, AleksandrGV commented on source/less/blocks/rates.less
> +.hit {
Исправил, сделал модификатором.

2020-08-31 16:13 UTC, AleksandrGV commented on source/less/blocks/slider.less
> +  width: 6px;
Исправил.

2020-08-31 16:22 UTC, AleksandrGV commented on source/less/blocks/user-stories.less
> +  height: 40px;
Исправил на min-height, но при переполнении происходит смещение самого блока вверх. Может верстка нужно другая?

2020-08-31 16:24 UTC, AleksandrGV commented on source/less/blocks/user-stories.less
> +  height: 40px;
Исправил на min-height, но при переполнении происходит смещение самого блока вверх. Может верстка нужна другая?

2020-08-31 16:33 UTC, AleksandrGV commented on source/photo.html
> +                      <div class="editing__toggle editing__toggle-contrast"></div>
Исправил.

2020-08-31 19:51 UTC, raccoonroman commented on source/less/blocks/user-stories.less
> +  height: 40px;
просто этот элемент нужно сделать абсолютом

2020-08-31 20:01 UTC, raccoonroman approved these changes

2020-08-31 20:01 UTC, raccoonroman commented on source/less/global/svg.less
> +  background-image: url("data:image/svg+xml,%3Csvg version='1.0' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='21.698px' height='16
имелось в виду, подключить как обычную свг картинку, а не как стили ;)

2020-08-31 20:02 UTC, merged

2020-09-01 07:24 UTC, AleksandrGV commented on source/index.html
> +            <article class="rates__article rates__hit">
Исправил.

2020-09-01 07:40 UTC, AleksandrGV commented on source/less/global/svg.less
> +  background-image: url("data:image/svg+xml,%3Csvg version='1.0' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='21.698px' height='16
Исправил.